# Generated by Django 4.1.7 on 2023-03-08 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saying', models.TextField(default='')),
                ('translation', models.TextField(default='')),
                ('category', models.CharField(choices=[(None, 'Misc'), ('Life', 'Life'), ('Patience', 'Patience'), ('Motivation', 'Motivation'), ('Gratitude', 'Gratitude'), ('Relationships', 'Relationships'), ('Love', 'Love'), ('Funny', 'Funny')], max_length=64)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
